on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    name: CI
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm test:v3
    - run: npm test:v4
    - run: npm test:latest