on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install --pure-lockfile  
    - run: yarn run test:v3
    - run: yarn run test:v4
    - run: yarn run test:v5
    - run: yarn run test:latest