on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install --pure-lockfile  
    - run: yarn run test:v3:raw
    - run: yarn run test:v4
    - run: yarn run test:v5
    - run: yarn run test:latest
    - env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
